
[package]
authors = ["Yao <yaojianpin@sohu.com>"]
description = "a fast, lightweight, extensiable workflow engine"
keywords = ["workflow"]
edition = "2024"
license = "Apache-2.0"
name = "acts"
homepage = "https://docs.rs/acts"
repository = "https://github.com/yaojianpin/acts.git"
include = ["src/**/*", "../LICENSE", "../README.md", "!**/tests/**/*"]
version.workspace = true

[dependencies]
tokio = { features = ["full", "macros"], workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
cron = { workspace = true }
globset = { default-features = false, workspace = true }
inventory = "0.3.20"
jsonschema = { version = "0.30.0", default-features = false }
nanoid = { workspace = true }
regex = { workspace = true }
rquickjs = { version = "0.13", features = ["macro", "parallel"] }
serde = { features = ["derive", "rc"], workspace = true }
serde_json = { workspace = true }
serde_repr = "0.1"
serde_yaml = { workspace = true }
strum = { features = ["derive"], workspace = true }
sha2 = "0.11"
thiserror = { workspace = true }
tracing = { workspace = true }
toml = { workspace = true }
dashmap = "6.1.0"
tokio-util = "0.7.18"
parking_lot = { workspace = true }
bitflags = { version = "2.13.1", features = ["serde"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio", "async_futures"] }
serial_test = { workspace = true }
tracing-subscriber = { features = ["env-filter"], workspace = true }
parking_lot = { workspace = true }

[[bench]]
harness = false
name = "workflow"
path = "../../benches/workflow.rs"

[[bench]]
harness = false
name = "store"
path = "../../benches/store.rs"

[[bench]]
harness = false
name = "engine"
path = "../../benches/engine.rs"

[[bench]]
harness = false
name = "model"
path = "../../benches/model.rs"

[[bench]]
harness = false
name = "latency"
path = "../../benches/latency.rs"

[[example]]
name = "simple"
path = "../../examples/simple/main.rs"

[[example]]
name = "model_build"
path = "../../examples/model_build/main.rs"

[[example]]
name = "actions"
path = "../../examples/actions/main.rs"

[[example]]
name = "approve"
path = "../../examples/approve/main.rs"

[[example]]
name = "catches"
path = "../../examples/catches/main.rs"

[[example]]
name = "event"
path = "../../examples/event/main.rs"

[[example]]
name = "message"
path = "../../examples/message/main.rs"

[[example]]
name = "custom_package"
path = "../../examples/custom_package/main.rs"

[[example]]
name = "subflow"
path = "../../examples/subflow/main.rs"

[[example]]
name = "timeout"
path = "../../examples/timeout/main.rs"

[[example]]
name = "user_var"
path = "../../examples/user_var/main.rs"

[[example]]
name = "resolver"
path = "../../examples/resolver/main.rs"

[[example]]
name = "prof"
path = "../../examples/prof/main.rs"

[[example]]
name = "while"
path = "../../examples/while/main.rs"
