
[workspace]
members = [
    "crates/*",
    "packages/*",
    "plugins/*",
    "examples/plugins/*",
    "examples/packages/*",
    "packages/acts-package-nats",
]
resolver = "3"

[workspace.package]
authors = ["Yao <yaojianpin@sohu.com>"]
description = "a fast, lightweight, extensiable workflow engine"
keywords = ["workflow"]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/yaojianpin/acts.git"
version = "0.23.0"

[workspace.dependencies]
tokio = { version = "1.52", features = ["full"] }
async-trait = { version = "0.1.88" }
serde = "1.0.219"
serde_json = "1.0.140"
strum = { version = "0.27", features = ["derive"] }
tonic = { version = "0.12", default-features = false, features = [
    "prost",
    "channel",
    "codegen",
] }
prost-types = "0.13"
axum = "0.7"
validator = { version = "0.20.0", features = ["derive"] }
futures-util = "0.3.31"
async-stream = "0.3.6"
anyhow = "1.0.100"
tokio-stream = "0.1.12"
acts-channel = { path = "./crates/acts-channel", version = "0.23.0" }
acts = { path = "./crates/acts", version = "0.23.0" }


[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true
