[package]
authors.workspace = true
description = "Acts workflow cli client"
keywords = ["workflow", "acts", "client"]
edition.workspace = true
license.workspace = true
name = "acts-cli"
repository.workspace = true
homepage = "https://github.com/yaojianpin/acts"
version.workspace = true

[dependencies]
acts-channel = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { version = "4.5.21", features = ["derive", "color", "env"] }
clap-cargo = "0.14.1"
comfy-table = "8.0.0"
futures = { workspace = true }
once_cell = "1.17.1"
owo-colors = "4.1.0"
regex = { workspace = true }
serde = { features = ["derive"], workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
shlex = "2"
tokio = { features = ["rt-multi-thread"], workspace = true }
