
cache_cap = 1024
tick_interval_secs = 15
max_message_retry_times = 20
max_node_run_times = 1000

[log]
dir = "data"
level = "INFO"

[db]
database_url = "./data"

# grpc service
[grpc]
port = 10080

# web service
[web]
port = 10082

# nats service
[nats]
url = "nats://localhost:4222"

[[nats.channels]]
id = "c1"
