[package]
authors.workspace = true
description = "A simple, fast, tiny acts workflow server"
keywords = ["workflow", "acts", "server"]
edition.workspace = true
license.workspace = true
name = "acts-server"
repository.workspace = true
homepage = "https://github.com/yaojianpin/acts"
version.workspace = true
rust-version.workspace = true

[dependencies]
acts-acl = { workspace = true }
anyhow = { workspace = true }
acts = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
time = { version = "0.3.36", features = ["macros"] }
tokio = { features = ["full"], workspace = true }
tracing = { workspace = true }
tracing-appender = "0.2.5"
tracing-subscriber = { features = [
    "local-time",
    "env-filter",
], workspace = true }
acts-package-http = { workspace = true }
acts-package-shell = { workspace = true }
acts-package-state = { workspace = true }
acts-package-nats = { workspace = true }
acts-package-javascript = { workspace = true }
acts-plugin-grpc = { workspace = true }
acts-plugin-web = { workspace = true }
acts-plugin-nats = { workspace = true }
acts-store = { workspace = true, features = ["sled", "sqlite", "postgres"] }
[dev-dependencies]
async-nats = { workspace = true }
async-trait = { workspace = true }
toml = { workspace = true }

[features]
default = []
