[package]
authors.workspace = true
description = "A simple, fast, tiny acts workflow server"
keywords = ["workflow", "acts", "server"]
edition.workspace = true
license.workspace = true
name = "acts-server"
repository.workspace = true
homepage = "https://github.com/yaojianpin/acts"
version.workspace = true

[dependencies]
anyhow = { workspace = true }
acts = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
time = { version = "0.3.36", features = ["macros"] }
tokio = { version = "1.26.0", features = ["full"] }
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.16", features = [
    "local-time",
    "env-filter",
] }
acts-package-http = { workspace = true }
acts-package-shell = { workspace = true }
acts-package-state = { workspace = true }
acts-package-nats = { workspace = true }
acts-plugin-grpc = { workspace = true }
acts-plugin-web = { workspace = true }
acts-plugin-nats = { workspace = true }
acts-channel = { workspace = true }
acts-store = { workspace = true, features = ["sled", "sqlite", "postgres", "redis", "nats"] }
[dev-dependencies]
async-nats = "0.50"

[features]
default = []
